services:
  backend:
    build:
      context: backend/
      dockerfile: config/dev/Dockerfile
    env_file: ./backend/config/dev/.env.postgres
    volumes:
      - ./backend/src:/app/src # Se aplica este volumen para que en desarrollo, todo cambio en el codigo recargue el microservicio
    depends_on:
      - db
    ports:
      - "8000:8000"

  frontend:
    build:
      context: frontend/
      dockerfile: config/dev/Dockerfile
    volumes:
      - ./frontend/src/:/app/src # Se aplica este volumen para que en desarrollo, todo cambio en el codigo recargue el microservicio
    ports:
      - "3000:3000" 

  db:
    container_name: database
    image: postgres:12.0-alpine
    env_file: ./backend/config/dev/.env.postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgres_data:
  static:
  media:
