services:
  backend:
    build:
      context: backend/
      dockerfile: config/prod/Dockerfile
    env_file: ./backend/config/prod/.env.postgres
    depends_on:
      - db
    ports:
      - "8000:8000"

  frontend:
    build:
      context: frontend/
      dockerfile: config/prod/Dockerfile
    ports:
    #  - "3000:3000" 
      - "80:80"

  db:
    container_name: database
    image: postgres:12.0-alpine
    env_file: ./backend/config/dev/.env.postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgres_data:
  static:
  media:
