apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  labels:
    app: db
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db
        image: postgres:12.0-alpine
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
        envFrom:
        - secretRef:
            name: db-env
        resources:
          requests:
            memory: "1Gi"
            cpu: "1000m" 
          limits:
            memory: "2Gi"
            cpu: "2000m"  
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-data

