name: CI/CD Pipeline for Nginx with DevSecOps

on:
  push:
    paths:
      - "ejercicio3/index.html"
      - "ejercicio3/Dockerfile"
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: |
          docker build -t my-nginx:latest .

  security:
    runs-on: ubuntu-latest
    needs: build 
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Scan Docker image for vulnerabilities with Trivy
        run: |
          docker pull my-nginx:latest  # Aseguramos que la imagen esté disponible
          trivy image --exit-code 1 --severity HIGH,CRITICAL my-nginx:latest || true  # El pipeline falla si hay vulnerabilidades críticas o altas

  push_image:
    runs-on: ubuntu-latest
    needs: security  
    steps:
      # 1. Login en DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image to DockerHub
        run: |
          docker tag my-nginx:latest <your-dockerhub-username>/my-nginx:latest
          docker push <your-dockerhub-username>/my-nginx:latest

  deploy:
    runs-on: ubuntu-latest
    needs: push_image 
    steps:

      - name: Deploy with Docker Compose
        run: |
          # Navigate to the directory containing docker-compose.yml
          cd ejercicio3
          docker-compose up -d

      - name: Verify Deployment
        run: |
          # Assuming the Nginx service is running on port 80
          echo "Checking if the service is running..."
          curl -s http://localhost:80 | grep "Bienvenidos a Nginx"