name: CI/CD Pipeline Nginx

on:
  push:
    paths:
      - "ejercicio3/index.html"
      - "ejercicio3/Dockerfile"
      - "ejercicio3/docker-compose.yml"
    branches:
      - main

jobs:
  code-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Placeholder for Code Tests
        run: |
          echo "Code Tests will be implemented here."

  security-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Test Dockerfile security with Conftest
        run: |
          docker run --rm $(pwd)/ejercicio3:/project openpolicyagent/conftest test --policy opa-docker-security.rego ejercicio3/Dockerfile

      - name: Static security analysis with Trivy
        run: |
          docker run --rm aquasec/trivy:latest fs --exit-code 1 --severity HIGH,CRITICAL . || true

  build-and-publish:
    runs-on: ubuntu-latest
    needs:
      - code-tests
      - security-tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: |
          cd ejercicio3/
          docker build -t ejercicio3-nginx:${{ github.sha }} .

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image to DockerHub
        run: |
          docker tag ejercicio3-nginx:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/ejercicio3-nginx:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/ejercicio3-nginx:${{ github.sha }}

          docker tag ejercicio3-nginx:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/ejercicio3-nginx:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/ejercicio3-nginx:latest

  prepare-deploy:
    runs-on: ubuntu-latest
    needs: build-and-publish
    steps:
      - name: Setup GCP CLI
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Start GCP VM for deployment
        run: |
          gcloud compute instances start ${{ secrets.GCP_INSTANCE_NAME }} --zone=us-central1-c

      - name: Schedule VM shutdown after 30 minutes
        run: |
          gcloud compute instances add-metadata ${{ secrets.GCP_INSTANCE_NAME }} \
            --zone=us-central1-c \
            --metadata shutdown-at=$(date -u -d "+30 minutes" +"%Y-%m-%dT%H:%M:%SZ")

      - name: Wait for instance to be ready
        run: |
          echo "Waiting for Instance to be ready"
          sleep 30

  deploy:
    runs-on: [self-hosted]
    needs: prepare-deploy
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy with Docker Compose
        run: |
          cd ejercicio3
          docker compose up -d --remove-orphans

      - name: Get Public IP Address
        id: public-ip
        run: |
          INSTANCE_IP=$(gcloud compute instances describe ${{ secrets.GCP_INSTANCE_NAME }} --zone=us-central1-c --format='get(networkInterfaces[0].accessConfigs[0].natIP)')
          echo "INSTANCE_IP=$INSTANCE_IP" >> $GITHUB_ENV

      - name: Verify Deployment
        run: |
          curl -s http://$INSTANCE_IP:80 | grep "Bienvenidos a Nginx"

      - name: Log Public URL
        run: |
          echo "Application deployed and accessible at: http://$INSTANCE_IP"

      - name: Post Public IP to GitHub UI
        uses: actions/github-script@v6
        with:
          script: |
            const instanceIP = process.env.INSTANCE_IP;
            core.summary.addHeading('Deployment Successful');
            core.summary.addLink(`Access your deployment at: http://${instanceIP}`, `http://${instanceIP}`);
            await core.summary.write();