name: CI/CD Pipeline Nginx

on:
  push:
    paths:
      - "ejercicio3/index.html"
      - "ejercicio3/Dockerfile"
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: |
          cd ejercicio3/
          docker build -t ejercicio3-nginx:latest .

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image to DockerHub
        run: |
          docker tag ejercicio3-nginx:latest lautarotorchia/ejercicio3-nginx:latest
          docker push lautarotorchia/ejercicio3-nginx:latest

  security:
    runs-on: ubuntu-latest
    needs: build 
    steps:

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Scan Docker image for vulnerabilities with Trivy
        run: |
          docker pull ejercicio3-nginx:latest  # Aseguramos que la imagen esté disponible
          trivy image --exit-code 1 --severity HIGH,CRITICAL ejercicio3-nginx:latest || true  # El pipeline falla si hay vulnerabilidades críticas o altas

  deploy:
    runs-on: ubuntu-latest
    needs: security 
    steps:

      - name: Deploy with Docker Compose
        run: |
          # Navigate to the directory containing docker-compose.yml
          cd ejercicio3
          docker-compose up -d

      - name: Verify Deployment
        run: |
          # Assuming the Nginx service is running on port 80
          echo "Checking if the service is running..."
          curl -s http://localhost:80 | grep "Bienvenidos a Nginx"